### ISSUE TITLE
Issues with the PDF

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#164]
Styling/typesetting in TeX:

 - [x] improve the leading in quotations (can't confirm/fixed in another way in #192)
 - [x] make hyphenation effective within `raggedright` text (figure captions/table titles) (PR#207)
 - [ ] enable margin content within boxes (checkout the techniques used in the implementation of the `marginfix` package)
 - [x] control `vspace` before and after quotations, figures and tables (PR #192)
 - [x] improve `\url` typesetting (breaks, links, typography, inside captions, etc.) (PR #192)

Generation improvements:

 - [ ] make the `\hline` as large as it needs to be, and position it correctly (note: don't make assumptions about `oneside`/`twoside` ... use the `idoddpage` package)
 - [x] reduce the load of `PositionTools.toLinePosition()` calls (4f98974518c4cd960954bf84a8135a342cdd8a08)
 - [ ] remove hard coded constants in `tex.LargeTable` that change depending on document settings (consider that the preamble is user defined with `\tex\preable`)
 - [ ] improve the table column size algo: (a) prioritize the first column when there are extra modules; (b) try to make column widths a bit more similar ("add" some "dampening" to the algo)

Check for possible typesetting issues:  
_(fix immediately if possible, otherwise simply report the problem with enough detail)_

 - [x] `vspace` before and after lists, boxes and headings (PR #207)
 - [ ] bad performance of the differently generated small/margin tables
 - [ ] incorrect/repeated markers under heavy list (`enumerate/itemize`) nesting
 - [ ] bad page breaking in the middle of a table
 - [ ] overflowing inline/display math
 - [ ] very large tables (see `[weak assert] would have FAILED: isum == available && tiny.length == 0` warnings from `manu`)

(note: when updating this checklist, don't reorder items)

**Comment by jonasmalacofilho** [comment]
Many long URLs overflow terribly.

For an example of this, check the typesetting of the URL bellow (from the sources at the bottom of [Table 2.8](https://brtguide.itdp.org/pull_request/170/guide/why-brt/performance#table:passengers-per-hour-per-peak-direction-observed-brt)).

```
https://www.itdp.org/more-development-for-your-transit-dollar-an-analysis-of-21-north-american-transit-corridors/
```
