### ISSUE TITLE
Issues with the online version

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#165]
Fixes:

 - [x] overflowing math (consider #101 if necessary) (PR #203)
 - [x] markers for (numbered/unnumbered) lists under heavy nesting (PR #204)
 - [x] properly style `DTitle` output (currently proxied by `DParagraph(Highlight(...))`) (PR #205)
 - [x] fix `\url` generation within captions (and, possibly, other elements) (PR #185)
 - [x] add _next_ link at the bottom of each page for linear readers (PR #189)

Additional output features:

 - [x] fix the generated headings levels for structural elements and figures/tables etc. (PR #185)
 - [x] implement "click to anchor/link" ~(and UI element to copy the link)~ to headings, figures, tables, boxes and paragraph titles (basically any vertical element with an id) (PR #185)
 - [x] fix placement of `id` attribute in figures for scrolls triggered by URL fragments (PR #185)
 - [ ] generate a [sitemap](https://support.google.com/webmasters/answer/156184?hl=en) to help external search engines, check #145 for possible additional requirements (WIP #179)

**Comment by craice** [comment]
**sitemap**

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"|urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <url>
    <loc>https://brtguide.itdp.org/branch/master/guide/</loc>
    <lastmod>2017-06-19</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>

  (...)

</urlset>
```

`<url>` : Parent tag for each URL entry.
`<loc>`:  URL of the page.
`<lastmod>`: The date of last modification of the file.
`<changefreq>`: How frequently the page is likely to change.
`<priority>`: The priority of this URL relative to other URLs on your site.

If we can set `lastmod` as the last time that page was changed, that would be better, but the last build will work too. The default `priority` of a page is 0.5 and I would use it for most of the pages and 1 for pages like the table of contents. I'm not sure about the `changefreq`parameter, I think that should be defined by the search engine.

for more: [https://www.sitemaps.org/protocol.html](url)

**Comment by jonasmalacofilho** [comment]
Id placement on figures causes issues when trying to link to them: since the ids are in the captions, the browser scroll _past_ the actual image when navigating to the corresponding fragment.

Btw, @craice, I guess I had already started [_experimenting_](88157c7ffcc0ab4a5978e9c5a40c62082c20b163) (without success) with the whole click-to-anchor thing.  I'm not even sure that commit can be cleanly applied anymore, but it might give you some insight.

**Comment by craice** [comment]
https://github.com/ITDP/the-online-brt-planning-guide/pull/203
https://github.com/ITDP/the-online-brt-planning-guide/pull/204
https://github.com/ITDP/the-online-brt-planning-guide/pull/205
